=== JavierGarRod/Lenguaje-de-marca/Javier_Garcia_AE_U5.1/Actividad1/Instituto_validacion.dtd
<!ELEMENT Instituto (Sedes, Ciclos, Asignaturas, Alumnos, Docentes, Matriculas)>

<!ELEMENT Sedes (Sede+)>
<!ELEMENT Sede (Nombre, Ciudad, Direccion)>
<!ATTLIST Sede 
    idSede ID #REQUIRED>

<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Ciudad (#PCDATA)>
<!ELEMENT Direccion (#PCDATA)>

<!ELEMENT Ciclos (Ciclo+)>
<!ELEMENT Ciclo (Nombre, Grado)>
<!ATTLIST Ciclo 
    idCiclo ID #REQUIRED>
<!ELEMENT Grado (#PCDATA)>

<!ELEMENT Asignaturas (Asignatura+)>
<!ELEMENT Asignatura (Nombre, Curso, CicloRef)>
<!ATTLIST Asignatura 
    idAsignatura ID #REQUIRED>
<!ELEMENT Curso (#PCDATA)>
<!ELEMENT CicloRef EMPTY>
<!ATTLIST CicloRef 
    idCiclo IDREF #REQUIRED>

<!ELEMENT Prerequisitos (Prerequisito+)>
<!ELEMENT Prerequisito EMPTY>
<!ATTLIST Prerequisito 
    idAsignaturaRef IDREF #REQUIRED>

<!ELEMENT Alumnos (Alumno+)>
<!ELEMENT Alumno (Nombre, Apellidos, TipoAcceso)>
<!ATTLIST Alumno 
    idAlumno ID #REQUIRED>
<!ELEMENT Apellidos (#PCDATA)>
<!ELEMENT TipoAcceso (#PCDATA)>

<!ELEMENT Docentes (Docente+)>
<!ELEMENT Docente (Nombre, Apellidos)>
<!ATTLIST Docente 
    idDocente ID #REQUIRED>
<!ELEMENT AsignaturaRef EMPTY>
<!ATTLIST AsignaturaRef 
    idAsignatura IDREF #REQUIRED>

<!ELEMENT Matriculas (Matricula+)>
<!ELEMENT Matricula (AlumnoRef, AsignaturaRef, CicloRef)>
<!ATTLIST Matricula 
    idMatricula ID #REQUIRED>
<!ELEMENT AlumnoRef EMPTY>
<!ATTLIST AlumnoRef 
    idAlumno IDREF #REQUIRED>

=== JavierGarRod/Lenguaje-de-marca/Javier_Garcia_AE_U5.1/Actividad1/Instituto_prueba1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Instituto SYSTEM "Instituto_validacion.dtd">
<Instituto>
    <Sedes>
        <Sede idSede="S1">
            <Nombre>I.E.S. Torre de los Guzmanes</Nombre>
            <Ciudad>La Algaba</Ciudad>
            <Direccion>c/Sanchez Cotán</Direccion>
        </Sede>
        <Sede idSede="S2">
            <Nombre>Salesianos Triana</Nombre>
            <Ciudad>Sevilla</Ciudad>
            <Direccion>...</Direccion>
        </Sede>
    </Sedes>

    <Ciclos>
        <Ciclo idCiclo="DAW">
            <Nombre>Desarrollo de Aplicaciones Web</Nombre>
            <Grado>Superior</Grado>
        </Ciclo>
        <Ciclo idCiclo="DAM">
            <Nombre>Desarrollo de Aplicaciones Multiplataforma</Nombre>
            <Grado>Superior</Grado>
        </Ciclo>
    </Ciclos>

    <Asignaturas>
        <Asignatura idAsignatura="BD">
            <Nombre>Base de Datos</Nombre>
            <Curso>1</Curso>
            <CicloRef idCiclo="DAW"/>
        </Asignatura>
        <Asignatura idAsignatura="PG">
            <Nombre>Programación</Nombre>
            <Curso>2</Curso>
            <CicloRef idCiclo="DAM"/>
        </Asignatura>
    </Asignaturas>

    <Alumnos>
        <Alumno idAlumno="A1">
            <Nombre>Javier</Nombre>
            <Apellidos>García</Apellidos>
            <TipoAcceso>Bachillerato</TipoAcceso>
        </Alumno>
        <Alumno idAlumno="A2">
            <Nombre>Pepe</Nombre>
            <Apellidos>Lozano</Apellidos>
            <TipoAcceso>Grado Medio</TipoAcceso>
        </Alumno>
    </Alumnos>

    <Docentes>
        <Docente idDocente="D1">
            <Nombre>Javier</Nombre>
            <Apellidos>Prada Oliva</Apellidos>
        </Docente>
    </Docentes>

    <Matriculas>
        <Matricula idMatricula="M1">
            <AlumnoRef idAlumno="A1"/>
            <AsignaturaRef idAsignatura="BD"/>
            <CicloRef idCiclo="DAM"/>
        </Matricula>
    </Matriculas>
</Instituto>

=== JavierGarRod/Lenguaje-de-marca/Javier_Garcia_AE_U5.1/Actividad1/Instituto_prueba2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Instituto SYSTEM "Instituto_validacion.dtd">
<Instituto>
    <Sedes>
        <Sede idSede="S1">
            <Nombre>I.E.S. Panaderos</Nombre>
            <Ciudad>Sevilla</Ciudad>
            <Direccion>Panaderia 52</Direccion>
        </Sede>
        <Sede idSede="S2">
            <Nombre>Centro Formativo San Marcos</Nombre>
            <Ciudad>Sevilla</Ciudad>
            <Direccion>Calle Feria</Direccion>
        </Sede>
    </Sedes>

    <Ciclos>
        <Ciclo idCiclo="DAM">
            <Nombre>Desarrollo de Aplicaciones Multiplataforma</Nombre>
            <Grado>Superior</Grado>
        </Ciclo>
    </Ciclos>

    <Asignaturas>
        <Asignatura idAsignatura="ETN">
            <Nombre>Entorno</Nombre>
            <Curso>1</Curso>
            <CicloRef idCiclo="DAM"/>
        </Asignatura>
        <Asignatura idAsignatura="SOST">
            <Nombre>Sostenibilidad</Nombre>
            <Curso>2</Curso>
            <CicloRef idCiclo="DAM"/>
        </Asignatura>
    </Asignaturas>

    <Alumnos>
        <Alumno idAlumno="A1">
            <Nombre>Lucía</Nombre>
            <Apellidos>Fernández Molina</Apellidos>
            <TipoAcceso>Bachillerato</TipoAcceso>
        </Alumno>
        <Alumno idAlumno="A2">
            <Nombre>Álvaro</Nombre>
            <Apellidos>Roldán Torres</Apellidos>
            <TipoAcceso>Grado Medio</TipoAcceso>
        </Alumno>
    </Alumnos>

    <Docentes>
        <Docente idDocente="D1">
            <Nombre>Marcos</Nombre>
            <Apellidos>Delgado Serrano</Apellidos>
        </Docente>
    </Docentes>

    <Matriculas>
        <Matricula idMatricula="M1">
            <AlumnoRef idAlumno="A1"/>
            <AsignaturaRef idAsignatura="ETN"/>
            <CicloRef idCiclo="DAM"/>
        </Matricula>
    </Matriculas>
</Instituto>
