=== JavierGarRod/Lenguaje-de-marca/intro_XML/instituto_validacion.dtd
<?xml version='1.0' encoding='ISO-8859-15'?>
  <!ELEMENT instituto (datos_instituto, ciclosFormativos, departamentos, docentes, alumnado, matricula)>

  <!ELEMENT datos_instituto (nombre_instituto)>
  <!ATTLIST datos_instituto
  total_alumnado CDATA #REQUIRED
  total_profesorado CDATA #REQUIRED>

  <!ELEMENT nombre_instituto (#PCDATA)>
  <!ELEMENT ciclosFormativos (#PCDATA)>
  <!ELEMENT departamentos (#PCDATA)>
  <!ELEMENT docentes (#PCDATA)>
  <!ELEMENT alumnado (#PCDATA)>
  <!ELEMENT matricula (#PCDATA)>

=== JavierGarRod/Lenguaje-de-marca/intro_XML/instituto_pruebas.xml
<?xml version='1.0' encoding='ISO-8859-15'?>
<!DOCTYPE instituto SYSTEM 'instituto_validacion.dtd' >
<instituto>
    <datos_instituto total_alumnado="350" total_profesorado="50">
        <nombre_instituto>I.E.S. Torre de los Guzmanes</nombre_instituto>
    </datos_instituto>
    <ciclosFormativos>
    </ciclosFormativos>
    <departamentos>
    </departamentos>
    <docentes>
    </docentes>
    <alumnado>
    </alumnado>
    <matricula>
    </matricula>
</instituto>
