=== JavierGarRod/Lenguaje-de-marca/ExamenT2/ExamenDTDyXML/ExamenDTD.dtd
<!--Elemento raíz-->
<!ELEMENT Aerolinea (Billetes, PrecioTipo, Vuelos)>

<!--Sección de Billetes-->
<!ELEMENT Billetes (Billete+)>
<!ELEMENT Billete (DNI, Telefono, Nombre, Apellidos, Tipo)>
<!--CodBillete = clave primaria-->
<!--CodVuelo = clave foránea hacia Vuelo-->
<!ATTLIST Billete
    CodBillete ID #REQUIRED
    CodVuelo IDREF #REQUIRED>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT Telefono (#PCDATA)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellidos (#PCDATA)>
<!ELEMENT Tipo (#PCDATA)>

<!--Sección PrecioTipo-->
<!ELEMENT PrecioTipo (Precio+)>
<!ELEMENT Precio (Coste)>
<!--Tipo = clave primaria-->
<!ATTLIST Precio
    Tipo ID #REQUIRED>
<!ELEMENT Coste (#PCDATA)>


<!--Sección Vuelos-->
<!ELEMENT Vuelos (Vuelo+)>
<!ELEMENT Vuelo (Origen, Destino, Fecha, Compania)>
<!--CodVuelo = clave primaria-->
<!ATTLIST Vuelo
    CodVuelo ID #REQUIRED>
<!ELEMENT Origen (#PCDATA)>
<!ELEMENT Destino (#PCDATA)>
<!ELEMENT Fecha (#PCDATA)>
<!ELEMENT Compania (#PCDATA)>

=== JavierGarRod/Lenguaje-de-marca/ExamenT2/ExamenDTDyXML/ExamenXML1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Aerolinea SYSTEM "ExamenDTD.dtd">

<Aerolinea>

    <Billetes>

        <Billete CodBillete="B1" CodVuelo="V1">
            <DNI>27663377L</DNI>
            <Telefono>653465465</Telefono>
            <Nombre>Juan</Nombre>
            <Apellidos>Ramirez López</Apellidos>
            <Tipo>Basico</Tipo>
        </Billete>

        <Billete CodBillete="B2" CodVuelo="V1">
            <DNI>32998877K</DNI>
            <Telefono>654321321</Telefono>
            <Nombre>Ana</Nombre>
            <Apellidos>García León</Apellidos>
            <Tipo>Premium</Tipo>
        </Billete>

        <Billete CodBillete="B3" CodVuelo="V2">
            <DNI>98889993H</DNI>
            <Telefono>954123432</Telefono>
            <Nombre>Javier</Nombre>
            <Apellidos>Sanz Amigo</Apellidos>
            <Tipo>Premium</Tipo>
        </Billete>

        <Billete CodBillete="B4" CodVuelo="V2">
            <DNI>11002233J</DNI>
            <Telefono>678943214</Telefono>
            <Nombre>Fatima</Nombre>
            <Apellidos>Pérez García</Apellidos>
            <Tipo>Basico</Tipo>
        </Billete>

    </Billetes>


    <PrecioTipo>

        <Precio Tipo="Basico">
            <Coste>170</Coste>
        </Precio>

        <Precio Tipo="Premium">
            <Coste>260</Coste>
        </Precio>

    </PrecioTipo>


    <Vuelos>

        <Vuelo CodVuelo="V1">
            <Origen>Sevilla</Origen>
            <Destino>Gran Canarias</Destino>
            <Fecha>14/03/2026</Fecha>
            <Compania>Vueling</Compania>
        </Vuelo>

        <Vuelo CodVuelo="V2">
            <Origen>Sevilla</Origen>
            <Destino>A Coruña</Destino>
            <Fecha>08/05/2026</Fecha>
            <Compania>Ryanair</Compania>
        </Vuelo>

    </Vuelos>

</Aerolinea>

<!--He cambiado todos los Cods para que esté todo mucho más claro-->

=== JavierGarRod/Lenguaje-de-marca/ExamenT2/ExamenDTDyXML/ExamenXML2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Aerolinea SYSTEM "ExamenDTD.dtd">

<Aerolinea>

    <Billetes>

        <Billete CodBillete="B5" CodVuelo="V4">
            <DNI>12345678A</DNI>
            <Telefono>123456789</Telefono>
            <Nombre>Luis</Nombre>
            <Apellidos>García Ortega</Apellidos>
            <Tipo>Basico</Tipo>
        </Billete>

        <Billete CodBillete="B6" CodVuelo="V4">
            <DNI>87654321B</DNI>
            <Telefono>987654321</Telefono>
            <Nombre>Elena</Nombre>
            <Apellidos>Pablo Delgado</Apellidos>
            <Tipo>Premium</Tipo>
        </Billete>

        <Billete CodBillete="B7" CodVuelo="V4">
            <DNI>11111111C</DNI>
            <Telefono>111111111</Telefono>
            <Nombre>Pepito</Nombre>
            <Apellidos>Pepe Almendro</Apellidos>
            <Tipo>Premium</Tipo>
        </Billete>

        <Billete CodBillete="B8" CodVuelo="V4">
            <DNI>22222222C</DNI>
            <Telefono>222222222</Telefono>
            <Nombre>Pepito</Nombre>
            <Apellidos>Grillo Naranjo</Apellidos>
            <Tipo>Basico</Tipo>
        </Billete>

    </Billetes>


    <PrecioTipo>

        <Precio Tipo="Basico">
            <Coste>150</Coste>
        </Precio>

        <Precio Tipo="Premium">
            <Coste>800</Coste>
        </Precio>

    </PrecioTipo>


    <Vuelos>

        <Vuelo CodVuelo="V4">
            <Origen>Sevilla</Origen>
            <Destino>Panamá</Destino>
            <Fecha>14/09/2026</Fecha>
            <Compania>Iberia</Compania>
        </Vuelo>

    </Vuelos>

</Aerolinea>

<!--He cambiado todos los Cods para que esté todo mucho más claro-->
<!--Soy un crack otro 10-->
